# Generated by Django 4.2.1 on 2023-05-05 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
